services:
  postgres:
    image: postgres:17
    container_name: postgres-kampus
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: kampus
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./Kampus.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
    driver: local
